name: Build

on:
  push:
    branches: '*'
    tags: '*'
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Docker Build
      run: make docker-build
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      if: startsWith(github.ref, 'refs/tags/')
      
    - name: Docker Push
      run: make docker-deploy
      if: startsWith(github.ref, 'refs/tags/')
